config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  resources :categories

  resources :items do 
    member do
      post :add_to_cart
    end

    resources :comments, only: [:create]
  end

  # cart
  # post "/abc/:id", to: "cart#add", as: :cc

  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      delete :cancel
    end
  end

  # users
  get "/login", to: "users#login"
  post "/login", to: "users#sign_in"
  delete "/logout", to: "users#logout"
  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"
  resource :user, only: [:edit, :update]

  # APIs
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do
          post :favorite
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def add_item(item_id)
    found_item = items.find { |item| item.item_id == item_id }

    if found_item
      found_item.increment!   # 增加數量
    else
      items << CartItem.new(item_id)
    end
  end

  def empty?
    items.empty?
  end

  def total
    result = items.sum { |item| item.total }

    # 4/1 全館打 1 折
    if Time.now.month == 4 and Time.now.day == 1
      result = result * 0.1
    end

    return result
  end

  def self.from_hash(hash = nil)
    if hash && hash["items"]
      items = hash["items"].map { |item|
        CartItem.new(item["item_id"], item["quantity"])
      }

      new(items)
    else
      new
    end
  end

  def to_hash
    items = @items.map { |item|  
      { "item_id" => item.item_id, "quantity" => item.quantity } 
    }

    return { "items" => items }
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :item_id, :quantity

  def initialize(item_id, quantity = 1)
    @item_id = item_id
    @quantity = quantity
  end

  def increment!(amount = 1)
    @quantity += amount
  end

  def item
    Item.find(item_id)
  end

  def total
    item.price * quantity
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :content, presence: true, length: { minimum: 2 }

  default_scope { where(deleted_at: nil).order(id: :desc) }
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :histories
  has_many :users, through: :histories
end

app/models/favorite_item.rb
class FavoriteItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, 
                    numericality: { greater_than: 0 }

  has_many :comments
  belongs_to :category

  has_many :favorite_items
  has_many :users, through: :favorite_items

  has_one_attached :cover

  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.now)
  end

  def favorited_by(u)
    u.items.include?(self)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  attr_reader :nonce

  belongs_to :user
  has_many :order_items

  before_create :create_order_num

  aasm column: 'state' do
    state :pending, initial: true
    state :paid, :delivered, :cancelled

    event :pay do
      transitions from: :pending, to: :paid

      after_transaction do
        puts "-" * 10
        puts "發送簡訊"
        puts "-" * 10
      end
    end

    event :deliver do
      transitions from: :paid, to: :delivered
    end

    event :cancel do
      transitions from: [:pending, :paid], to: :cancelled
    end
  end

  private

  def create_order_num
    self.order_num = num_generator
  end

  def num_generator
    # 實作內容
    year = Date.today.year
    month = Date.today.month
    day = Date.today.day
    code = [*0..9, *'A'..'Z'].sample(6).join

    # 20200427A8E1E9
    "#{year}#{"%02d" % month}#{"%02d" % day}#{code}"
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 4 }, presence: true, on: :create
  validates :password, confirmation: true

  has_many :histories
  has_many :events, through: :histories
  has_many :comments

  has_many :favorite_items
  has_many :items, through: :favorite_items

  has_many :orders

  def displayname
    self.nickname == "" ? self.email : self.nickname
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def destroy
    session[:carty] = nil
    redirect_to root_path, notice: '購物車已清空'
  end

  def checkout
    @order = Order.new
    @token = gateway.client_token.generate
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy, :add_to_cart] 

  def index
    @items = Item.page(params[:page]).per(6)
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)  # eager loading
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path, notice: '成功新增餐點!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: '成功更新餐點!'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: '成功刪除餐點'
  end

  def add_to_cart
    current_cart.add_item(@item.id)
    session[:carty] = current_cart.to_hash
    
    render json: { items_count: current_cart.items.count }
  end

  private
  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, 
                                 :description, 
                                 :price, 
                                 :category_id,
                                 :cover,
                                 :spec)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_login

  def login
    @user = User.new
  end

  def sign_up
    @user = User.new
  end

  def sign_in
    user = User.find_by(email: user_params[:email])

    if user && user.authenticate(user_params[:password])
      session[:ccc9527] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def registration
    @user = User.new(user_params)
    if @user.save
      session[:ccc9527] = @user.id
      # TODO: 密碼加密
      redirect_to root_path
    else
      # 失敗
      render :sign_up
    end
  end

  def logout
    reset_session
    redirect_to root_path
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(update_params)
      redirect_to root_path, notice: 'user updated!'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:email,
                                 :nickname, 
                                 :password, 
                                 :password_confirmation)
  end

  def update_params
    if params[:user][:password].blank?
      params.require(:user).permit(:nickname,
                                   :tel,
                                   :name)
    else
      params.require(:user).permit(:nickname,
                                   :tel,
                                   :name,
                                   :password,
                                   :password_confirmation)
    end  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinbendon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :head_js %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert" data-controller="flash" data-target="flash.message">
    <%= notice %>
    <button type="button" class="close" data-action="flash#close">
     <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert" data-controller="flash" data-target="flash.message">
    <%= alert %>
    <button type="button" class="close" data-action="flash#close">
     <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer font-small bg-light mt-2">
  <div class="footer-copyright text-center py-2">2020 &copy;
    <%= link_to "吃飯", root_path %>
  </div>
</footer> 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "訂便當", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "餐點列表", items_path, class: 'nav-link' %>
      </li>

      <% if current_user %>
        <li class="nav-item">
          <%= link_to "我要開團", "#", class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <a href="/sign_up" class="nav-link">註冊</a>
        </li>
        <li class="nav-item">
          <a href="/login" class="nav-link">登入</a>
        </li>
      <% end %>
    </ul>

    <% if current_user %>
    <ul class="navbar-nav">
      <li data-controller = "cart" data-target="cart.myCart">
        <%= link_to cart_path, class: 'nav-link' do %>
          購物車 <i class="fas fa-shopping-cart"></i> 
          <span data-target="cart.cartCounter" data-action="addItemToCart@document->cart#updateCart"><%= current_cart.items.count %></span>
        <% end %>
      </li>
      <li>
        <a href="/user/edit" class="nav-link">日安，<%= current_user.displayname %></a>
      </li>
      <li class="nav-item">
        <%= link_to "登出", logout_path, method: 'delete', class: 'nav-link' %>
      </li>
    </ul>
    <% end %>
  </div>
</nav>