config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  resources :categories

  resources :items do 
    member do
      post :add_to_cart
    end

    resources :comments, only: [:create]
  end

  # cart
  # post "/abc/:id", to: "cart#add", as: :cc

  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      delete :cancel
    end
  end

  # users
  get "/login", to: "users#login"
  post "/login", to: "users#sign_in"
  delete "/logout", to: "users#logout"
  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"
  resource :user, only: [:edit, :update]

  # APIs
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do
          post :favorite
        end
      end
    end
  end
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def add_item(item_id)
    found_item = items.find { |item| item.item_id == item_id }

    if found_item
      found_item.increment!   # 增加數量
    else
      items << CartItem.new(item_id)
    end
  end

  def empty?
    items.empty?
  end

  def total
    result = items.sum { |item| item.total }

    # 4/1 全館打 1 折
    if Time.now.month == 4 and Time.now.day == 1
      result = result * 0.1
    end

    return result
  end

  def self.from_hash(hash = nil)
    if hash && hash["items"]
      items = hash["items"].map { |item|
        CartItem.new(item["item_id"], item["quantity"])
      }

      new(items)
    else
      new
    end
  end

  def to_hash
    items = @items.map { |item|  
      { "item_id" => item.item_id, "quantity" => item.quantity } 
    }

    return { "items" => items }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def destroy
    session[:carty] = nil
    redirect_to root_path, notice: '購物車已清空'
  end

  def checkout
    @order = Order.new
    @token = gateway.client_token.generate
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% if not current_cart.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>餐點</th>
        <th>數量</th>
        <th>小計</th>
      </tr>
    </thead>
    <tbody>
      <% current_cart.items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.item.name %> (<%= cart_item.item.price %>元)</td>
        <td><%= cart_item.quantity %></td>
        <td><%= cart_item.total %></td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2">總計</td>
        <td><%= current_cart.total %></td>
      </tr>
    </tfoot>
  </table>
<% end %>

app/views/carts/checkout.html.erb
<%= content_for :head_js do %>
  <script src="https://js.braintreegateway.com/web/dropin/1.22.1/js/dropin.min.js"></script>
<% end %>

<h1>結帳</h1>

<%= render 'cart' %>

<%= form_for(@order) do |form| %>
  <div>
    <%= form.label :receiver %>
    <%= form.text_field :receiver %>
  </div>
  
  <div>
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <%= form.hidden_field :nonce %>

  <div id="dropin-container"></div>

  <%= form.submit id: 'submit-order' %>
<% end %>

<script>
  document.addEventListener("turbolinks:load", function() {
    let button = document.querySelector("#submit-order");
    let nonce_field = document.querySelector("#order_nonce");
    let form = document.querySelector("#new_order");

    braintree.dropin.create({
      authorization: '<%= @token %>',
      container: '#dropin-container'
    }, function (createErr, instance) {
      button.addEventListener('click', function (e) {
        e.preventDefault();
        instance.requestPaymentMethod(function (err, payload) {
          nonce_field.value = payload.nonce;
          form.submit();
        });
      });
    });
  });

</script>

app/views/carts/show.html.erb
<h1>
  購物車
  <%= link_to "清空購物車", cart_path, method: 'delete', class: 'btn btn-sm btn-success' unless current_cart.empty? %>
</h1>

<%= render 'cart' %>

<%= link_to "繼續選購", root_path, class: 'btn btn-primary' %>
<%= link_to "結帳", checkout_cart_path, class: 'btn btn-danger' unless current_cart.empty? %>