config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  resources :categories

  resources :items do 
    member do
      post :add_to_cart
    end

    resources :comments, only: [:create]
  end

  # cart
  # post "/abc/:id", to: "cart#add", as: :cc

  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, only: [:index, :show, :create] do
    member do
      delete :cancel
    end
  end

  # users
  get "/login", to: "users#login"
  post "/login", to: "users#sign_in"
  delete "/logout", to: "users#logout"
  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"
  resource :user, only: [:edit, :update]

  # APIs
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do
          post :favorite
        end
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, 
                    numericality: { greater_than: 0 }

  has_many :comments
  belongs_to :category

  has_many :favorite_items
  has_many :users, through: :favorite_items

  has_one_attached :cover

  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.now)
  end

  def favorited_by(u)
    u.items.include?(self)
  end
end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < ApplicationController
  def favorite
    item = Item.find(params[:id])

    if item.favorited_by(current_user)
      current_user.items.delete(item)
      render json: {status: 'removed'}
    else
      current_user.items << item
      render json: {status: 'favorited'}
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy, :add_to_cart] 

  def index
    @items = Item.page(params[:page]).per(6)
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)  # eager loading
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path, notice: '成功新增餐點!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: '成功更新餐點!'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: '成功刪除餐點'
  end

  def add_to_cart
    current_cart.add_item(@item.id)
    session[:carty] = current_cart.to_hash
    
    render json: { items_count: current_cart.items.count }
  end

  private
  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, 
                                 :description, 
                                 :price, 
                                 :category_id,
                                 :cover,
                                 :spec)
  end
end

app/helpers/api/v1/items_helper.rb
module Api::V1::ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>

  <% if item.errors.any? %>
    <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :cover %>
    <%= f.file_field :cover %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.label :spec %>
    <%= f.text_field :spec %>
  </div>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>編輯餐點</h1>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<h1>餐點列表</h1>

<%= link_to "新增", new_item_path %>

<div class="row">
  <% @items.each do |item| %>
    <div class="col-4 item">
      <div class="card">
        <div class="cover-item">
          <%= image_tag item.cover.variant(resize_to_limit: [200, 200]), class: 'cover-image' if item.cover.attached? %>
        </div>
        <div class="card-body" data-controller="item">
          <h5 class="card-title">
            <%= link_to item.name, item %>
          </h5>
          <input type="hidden" data-target="item.itemId" value="<%= item.id %>">
          <%= link_to "編輯", edit_item_path(item), class: 'btn btn-primary' %>
          <%= link_to "刪除", item, method: 'delete', data: {confirm: "是否確認刪除?"}, class: 'btn btn-success' %>
          <%= button_tag "加到購物車", method: 'post', class: 'btn btn-danger', data: {action: 'item#addItem'} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="item-pagination">
  <%=  paginate @items %>
</div>

app/views/items/new.html.erb
<h1>新增餐點</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<h1 data-controller="item">
  <%= @item.name %>(<%= @item.price %> 元)
  <a href="#" class="btn btn-danger" data-action="item#heart">
    <% if @item.favorited_by(current_user) %>
      <i class="fas fa-heart" data-target="item.icon"></i>
    <% else %>
      <i class="far fa-heart" data-target="item.icon"></i>
    <% end %>
  </a>
  <input type="hidden" data-target="item.item_id" value="<%= @item.id %>">
  <%= button_tag "加到購物車", method: 'post', class: 'btn btn-danger', data: {action: 'item#additem'} %>
</h1>

<%= image_tag @item.cover.variant(resize_to_limit: [500, 500]), class: 'cover-image' if @item.cover.attached? %>

<div data-controller="comment">
  <h3>留言</h3>
  <%= form_for(@comment, url: item_comments_path(@item), remote: true) do |form| %>
    <input type="hidden" id="item_id" value="<%= @item.id %>">
    <div class="form-group">
      <%= form.text_area :content, 
                         class: 'form-control', 
                         data: {target: 'comment.content', 
                                action: 'keyup->comment#check' } %>
    </div>

    <%= form.submit class: 'btn btn-success', disabled: true, data: {target: 'comment.submit' } %>
  <% end %>
</div>

<hr>

<div id="comments">
<% @comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>
</div>